### ISSUE TITLE
[BUG] Setup device auth doesn't show any trakt code

### ISSUE THREAD

**Issue by GMFalka** [iamkroot/trakt-scrobbler#32]
**Describe the bug**
While running windows install bat, the trakt "activate your device" page comes up, but theres no code in the cmd window

**Desktop (please complete the following information):**
 - OS:  windows
 - Python Version:  3.8

```
C:\WINDOWS\system32>"C:\Users\usernameDesktop\trakt-scrobbler-master\scripts\windows-install.bat"
Checking pipenv install.

Checking config file
config.toml already exists in "C:\Users\username\AppData\Roaming\trakt-scrobbler\".
Please ensure that it matches sample_config.toml, or the app may crash unexpectedly.

Installing to "C:\Users\username\AppData\Local\trakt-scrobbler"
File not found - trakt_scrobbler
File not found - Pipfile
File not found - Pipfile.lock
Installing dependencies from Pipfile.lock (dc303a)…
Ignoring dbus-python: markers 'sys_platform == "linux"' don't match your environment
Ignoring notify2: markers 'sys_platform != "win32"' don't match your environment
  ================================ 16/16 - 00:00:02
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
Setup complete. Starting device authentication.
```

</p>
</details>

**Comment by GMFalka** [comment]
Thank you for the fast response!

I read the instructions and i tried from root too.
Root is `C:\Users\usernameDesktop\trakt-scrobbler-master\` , right?

**Comment by iamkroot** [comment]
Hmm this is weird indeed. Could you send the contents of `trakt_token.json` file in `C:\Users\username\AppData\Roaming\trakt-scrobbler`?

**Comment by GMFalka** [comment]
Thank you for your time!

`trakt_token.json` doesn't exist. Not while or after the `install.bat`

**Comment by iamkroot** [comment]
Quick question, are you running the script as an admin? Maybe try with a normal user? If not, we'll have to manually debug the error by calling the trakt authentication logic in a shell.

**Comment by GMFalka** [comment]
I tried with and without admin rights.
Posting the manual command would be appreciated!

**Comment by iamkroot** [comment]
Sorry for the late reply, here's the commands:
1. `cd` to `C:\Users\username\AppData\Local\trakt-scrobbler`
2. Enter `pipenv run python`. You should get the Python REPL shell here.
3. Type `import trakt_interface as ti`
4. Enter `print(ti.TRAKT_TOKEN_PATH)`. It should match `C:\Users\username\AppData\Roaming\trakt-scrobbler\trakt_token.json`.
5. Run `print(ti.token_data)`. It should be `None` for now.
6. To start the authentication, run `ti.get_access_token()` and follow the instructions it shows. If all goes well, your token should be saved, and you can restart the install script.

**Comment by GMFalka** [comment]
Appreciate your time!

I followed your guide, still no code being shown :/ 

Its just shows  the trakt code webpage and the cmd window doesn't show the code.
I CTRL-X'd out and this is the output, does it help anything?

```
C:\Users\username\AppData\Local\trakt-scrobbler>pipenv run python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import trakt_interface as ti
>>> print(ti.TRAKT_TOKEN_PATH)
C:\Users\username\AppData\Roaming\trakt-scrobbler\trakt_token.json
>>> print(ti.token_data)
None
>>> ti.get_access_token()

----This is where i ctrl-X'd out after a few minutes.----

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\username\AppData\Local\trakt-scrobbler\trakt_interface.py", line 106, in get_access_token
    token_data = device_auth()
  File "C:\Users\username\AppData\Local\trakt-scrobbler\trakt_interface.py", line 71, in device_auth
    time.sleep(int(code_data['interval']))
KeyboardInterrupt
>>> ^X
```

If i delete the trakt_token.json file, it doesn't recreate it.

**Comment by iamkroot** [comment]
We'll have to dive deeper now. Open up `C:\Users\username\AppData\Local\trakt-scrobbler\trakt_interface.py` in your text editor, and on line 11, write `logger.info = logger.debug = print`. Save it and then redo the steps given above. It should hopefully print some messages.

**Comment by iamkroot** [comment]
Hey @GMFalka I've updated the code to fix the logging. You can download the latest version of the app and run the install script again. It should now hopefully log the cause of your error in `C:\Users\username\AppData\Roaming\trakt-scrobbler\trakt_scrobbler.log`. Do give it a try when you have time!

**Comment by GMFalka** [comment]
I really appreciate your time!

Deleted all the old stuff from local and roaming and started the installer again, There were no errors about missing files (but no trakt code) and the logging file says
`2019-11-01 12:20:50,266 - ERROR - MainThread - utils - config.toml not found!`

I tried putting the config file everywhere,  but still the same error.

**Comment by GMFalka** [comment]
Maybe because my windows username is two words with a space?  "user name"

**Comment by iamkroot** [comment]
> 2019-11-01 12:20:50,266 - ERROR - MainThread - utils - config.toml not found!

Ah damn, that's my fault sorry. I didn't test the new code on windows before pushing it, and the app was looking in the wrong folder for the config file. I'll push a bugfix ASAP

**Comment by iamkroot** [comment]
Fixed. Try now please.

**Comment by GMFalka** [comment]
It works! :)

The cmd window did not shown any code tho, so i had to dig into the log file and i found the code there.

It would be great if you could print that code into the install cmd window.

heres the log file: (i deleted the datetimes for easy read)

```
 - MainThread - utils - C:\Users\username\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
 - MainThread - utils - C:\Users\username\AppData\Roaming\trakt-scrobbler\trakt_token.json doesn't exist.
 - MainThread - trakt_interface - Access token not found in config. Initiating device authentication.
 - MainThread - trakt_interface - Verification URL: https://trakt.tv/activate
 - MainThread - trakt_interface - User Code: xxxxxxxx
 - MainThread - trakt_interface - Waiting for user to authorize app.
 - MainThread - trakt_interface - Waiting for user to authorize app.
 - MainThread - trakt_interface - Waiting for user to authorize app.
 - MainThread - trakt_interface - Waiting for user to authorize app.
 - MainThread - trakt_interface - Waiting for user to authorize app.
 - MainThread - trakt_interface - Waiting for user to authorize app.
 - MainThread - trakt_interface - Waiting for user to authorize app.
 - MainThread - trakt_interface - Waiting for user to authorize app.
 - MainThread - trakt_interface - Waiting for user to authorize app.
 - MainThread - trakt_interface - Device auth successful.
 - MainThread - utils - C:\Users\username\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
 - MainThread - scrobbler - Started scrobbler thread.
 - MainThread - utils - C:\Users\username\AppData\Roaming\trakt-scrobbler\watched_cache.json doesn't exist.
- MainThread - monitor - Started monitor for mpchc
```

**Comment by iamkroot** [comment]
As I suspected, this seems to be a bug with your notifications :P
The app is supposed to show a popup notification of the user code, but it wasn't shown in your system. Can you check whether notifications are shown when playing files?

**Comment by GMFalka** [comment]
I didnt know it was supposed to show a windows notification :(

I did disabled and enabled the windows notification center in the past years. Now its enabled but no codes were shown.

Wouldnt it be easier for the user to just print the code in the cmd?

Also if you have a paypal, i would love to donate some coffe/beer money.

**Comment by iamkroot** [comment]
> Now its enabled but no codes were shown.

That is weird indeed. Also, I'm curious. The app is supposed to automatically open the activation page on your default browser (unrelated to notification module). Did even that not happen with you?


> Wouldnt it be easier for the users to just print the code for them in the cmd?

That does sound better, thanks for the suggestion. I'll update the app.


> Also if you have a paypal, i would love to donate some coffe/beer money.

Thanks for the offer, I'm flattered, but I just made this app cuz I saw a problem and I wanted to fix it. I'm happy that it is becoming useful for others too! If you really wanna contribute, I suggest donating to your favorite charity ^-^. That'll probably do more good than me drinking a coffee :P

Glad to have your problem sorted out, and please don't hesitate to ping me in case you find more bugs :D

**Comment by GMFalka** [comment]
> > Now its enabled but no codes were shown.
> 
> That is weird indeed. Also, I'm curious. The app is supposed to automatically open the activation page on your default browser (unrelated to notification module). Did even that not happen with you?
> 


The webpage came up every time. Basicly everything was working with that app, only my windows did not shown any notificaiton about the code :) 
Showing it in the cmd window will be much cleaner too, i think. Also 1 less dependancy?

Thank you again. Im a huge home automation guy with a homelab and lots of diy things, so i was looking for a working trakt scrobbler for years!

**Comment by iamkroot** [comment]
> Showing it in the cmd window will be much cleaner too, i think.

Done!


> Also 1 less dependency?

Not really, a notification is shown every time the scrobbling starts. Kinda helps catch any mis-identifications, and I can know that the app is alive and working well :P

**Comment by GMFalka** [comment]
Hi @iamkroot 

Tried updating the scrobbler. 
Installer gets stuck at this:

```
  File "C:\Users\username\.virtualenvs\trakt-scrobbler-DTMn-yQC\lib\site-packages\toml\decoder.py", line 914, in load_array
    a[b] = a[b] + ',' + a[b + 1]
IndexError: list index out of range
```

Full log:
```
C:\Users\username\Desktop\trakt-scrobbler-master>windows-install.bat
Checking pipenv install.

Checking config file
config.toml already exists in "C:\Users\username\AppData\Roaming\trakt-scrobbler\".
Please ensure that it matches sample_config.toml, or the app may crash unexpectedly.

Installing to "C:\Users\username\AppData\Local\trakt-scrobbler"
Creating a virtualenv for this project…
Pipfile: C:\Users\username\AppData\Local\trakt-scrobbler\Pipfile
Using c:\users\username\appdata\local\programs\python\python38-32\python.exe (3.8.0) to create virtualenv…
[ ===] Creating virtual environment...Already using interpreter c:\users\username\appdata\local\programs\python\python38-32\python.exe
Using base prefix 'c:\\users\\username\\appdata\\local\\programs\\python\\python38-32'
New python executable in C:\Users\CONSTI~1\VIRTUA~1\TRAKT-~1\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

Successfully created virtual environment!
Virtualenv location: C:\Users\username\.virtualenvs\trakt-scrobbler-DTMn-yQC
Installing dependencies from Pipfile.lock (6191d4)…
Ignoring dbus-python: markers 'sys_platform == "linux"' don't match your environment
Ignoring notify2: markers 'sys_platform != "win32"' don't match your environment
  ================================ 17/17 - 00:00:06
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
Setup complete. Starting device authentication.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\username\AppData\Local\trakt-scrobbler\trakt_interface.py", line 8, in <module>
    from notifier import notify
  File "C:\Users\username\AppData\Local\trakt-scrobbler\notifier.py", line 2, in <module>
    from utils import config
  File "C:\Users\username\AppData\Local\trakt-scrobbler\utils.py", line 59, in <module>
    config = read_toml(CFG_DIR / 'config.toml')
  File "C:\Users\username\AppData\Local\trakt-scrobbler\utils.py", line 16, in read_toml
    return toml.load(file_path)
  File "C:\Users\username\.virtualenvs\trakt-scrobbler-DTMn-yQC\lib\site-packages\toml\decoder.py", line 112, in load
    return loads(ffile.read(), _dict, decoder)
  File "C:\Users\username\.virtualenvs\trakt-scrobbler-DTMn-yQC\lib\site-packages\toml\decoder.py", line 455, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "C:\Users\username\.virtualenvs\trakt-scrobbler-DTMn-yQC\lib\site-packages\toml\decoder.py", line 725, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "C:\Users\username\.virtualenvs\trakt-scrobbler-DTMn-yQC\lib\site-packages\toml\decoder.py", line 802, in load_value
    return (self.load_array(v), "array")
  File "C:\Users\username\.virtualenvs\trakt-scrobbler-DTMn-yQC\lib\site-packages\toml\decoder.py", line 914, in load_array
    a[b] = a[b] + ',' + a[b + 1]
IndexError: list index out of range
"You can run this script again once the issue is fixed. Quitting."
```
